### ISSUE TITLE
Embed gists limit?

### ISSUE THREAD

**Issue by poshwaffle** [blairvanderhoof/gist-embed#66]
I'm using your script to embed multiple gists to a knowledge base article and there are just over 70 gists on the one page. However, after the 40th gist, the other remaining gists failed to load and page displays the following error:

`Failed loading gist https://gist.github.com/xxxxx.json: timeout`

Is this a limit with the Gist API?

**Comment by blairvanderhoof** [comment]
Hi @poshwaffle, sorry to hear that. I'm not aware of rate limits. Could you possibly not render everything at once? Maybe a lazy load on scroll?  Regardless of the rate limits, your approach could cause jank in the browser since it will be firing off 70 network requests on load and rendering all of that DOM in succession.

**Comment by poshwaffle** [comment]
Yeah, thats what I was thinking. Probably need to split the doc up. Thanks for replying.

**Comment by blairvanderhoof** [comment]
Good luck, let me know how it works out.
